// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Pp81FcRAnLGr71_HGNSwPfJGSExYG1A',
    appId: '1:1040930402944:web:f4bb8b0ac2e97fb213ec65',
    messagingSenderId: '1040930402944',
    projectId: 'fire-drive-69a2f',
    authDomain: 'fire-drive-69a2f.firebaseapp.com',
    storageBucket: 'fire-drive-69a2f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy_WKDxsVFbqTVCeRpWhUPennUT_rUmxo',
    appId: '1:1040930402944:android:1a248d3c5d8a93f813ec65',
    messagingSenderId: '1040930402944',
    projectId: 'fire-drive-69a2f',
    storageBucket: 'fire-drive-69a2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbNJ4coFhBX1RaLwmlEQgpObf_iYQiUP4',
    appId: '1:1040930402944:ios:c28752a43dfae05913ec65',
    messagingSenderId: '1040930402944',
    projectId: 'fire-drive-69a2f',
    storageBucket: 'fire-drive-69a2f.appspot.com',
    iosBundleId: 'com.example.fireDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbNJ4coFhBX1RaLwmlEQgpObf_iYQiUP4',
    appId: '1:1040930402944:ios:fe2f45b619aa43f013ec65',
    messagingSenderId: '1040930402944',
    projectId: 'fire-drive-69a2f',
    storageBucket: 'fire-drive-69a2f.appspot.com',
    iosBundleId: 'com.example.fireDrive.RunnerTests',
  );
}
